server:
  port: 8081

raif:
  sbpMerchantId: "MA622976"
  secretKey: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNQTYyMjk3NiIsImp0aSI6ImM5MTBjNGU4LTRhZmMtNDBlMS04ZGU3LWVlODg2N2JiOGU3NCJ9.rnPFEsixy9Wr4GhxT9D9s8dlBg5dRKWMLPfxl48oHAo"

notification:
  callback:
    value: "https://pay-test.raif.ru/api/settings/v1/callback"
  url:
    value: "http://147.78.66.234:8081/payment-api/v1/notification"